"use client"
import './globals.css'
import { AuthContextProvider } from "./context/AuthContext";
import { Layout } from 'antd';
import { Content } from 'antd/es/layout/layout';
import Header from './components/Header';
import MyFooter from './components/Footer';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

//! Find a way to export metadata from client components
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Layout>
            <Header />

            <Content style={{ height: "100vh" }}>
              {children}
            </Content>
            {/* //todo: add back after fixing footer styles */}
            {/* <MyFooter /> */}
          </Layout>
        </AuthContextProvider>
      </body>
    </html>
  )
}
